// GENERATED by tools/build_vendors.py from the species alias table,
// checked against each vendor's catalog. Do not edit by hand -- edit
// the table and re-run. ASCII only: status.html declares no charset.
var VENDORS = {
 "lists": {
  "seedntree": {
   "label": "Seed 'n' Tree",
   "dated": "2026 list, rec'd 7/1/26"
  },
  "bron": {
   "label": "Bron & Sons",
   "dated": "2027 booking form"
  },
  "mckay": {
   "label": "McKay",
   "dated": "list of 7/20/26"
  },
  "stewart": {
   "label": "Stewart Bros",
   "dated": "2025-26 availability, no prices"
  }
 },
 "species": {
  "abbottswood-potentilla": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Abbotswood Potentilla",
      "forms": [
       [
        "#1",
        8.17
       ],
       [
        "#2",
        14.24
       ],
       [
        "#5",
        23.79
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": [
     {
      "as": "Abbotswood Potentilla",
      "forms": [
       [
        "1QT",
        null
       ]
      ]
     }
    ]
   }
  },
  "alaska-flag-iris": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Iris\u2026Alaskan",
      "forms": [
       [
        "#1",
        8
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Arctic Iris",
      "forms": [
       [
        "#1",
        7.83
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "alpine-currant": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Alpine currant",
      "forms": [
       [
        "#5",
        46
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Alpine Currant",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Alpine Currant",
      "forms": [
       [
        "#3 Container",
        18.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "amur-maple": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Amur maple",
      "forms": [
       [
        "#5",
        48
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Amur Maple",
      "forms": [
       [
        "#1 Shrub",
        7.88
       ],
       [
        "#2 Shrub",
        14.53
       ],
       [
        "#5 Shrub",
        22.98
       ],
       [
        "#10 Shrub",
        45.53
       ],
       [
        "#5 Tree",
        45.2
       ],
       [
        "#10 Tree",
        83.61
       ],
       [
        "#15 Tree",
        115.56
       ]
      ]
     }
    ],
    "mckay": null
   }
  },
  "birchleaf-spirea": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Birch leaf Tor",
      "forms": [
       [
        "#5",
        48
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Tor Birchleaf Spirea",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     },
     {
      "as": "White Birchleaf Spirea",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Tor Birchleaf Spirea",
      "forms": [
       [
        "#3 Container",
        18.5
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "bishop-s-weed-goutweed": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Variegated Goutweed",
      "forms": [
       [
        "#1",
        7.83
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "colorado-green-spruce": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Colorado blue and green spruce, Ak. grown",
      "forms": [
       [
        "4'-5'",
        245
       ],
       [
        "5'-6'",
        325
       ]
      ]
     },
     {
      "as": "Colorado green spruce. Idaho, Specimen trees",
      "forms": [
       [
        "7'-8'",
        1128
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Colorado Spruce",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        15.81
       ],
       [
        "#5",
        26.11
       ],
       [
        "#10 HT 75-90cm",
        81.37
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Colorado Blue Spruce",
      "forms": [
       [
        "5' Balled & Burlap",
        162.75
       ]
      ]
     }
    ],
    "stewart": [
     {
      "as": "Colorado Spruce",
      "forms": [
       [
        "#25 7-8'",
        null
       ]
      ]
     }
    ]
   }
  },
  "columnar-swedish-aspen": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Swedish columnar aspen",
      "forms": [
       [
        "2.00\"",
        606
       ],
       [
        "2.25\"",
        636
       ],
       [
        "2.5\"",
        650
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Swedish Columnar Aspen",
      "forms": [
       [
        "#2",
        16.81
       ],
       [
        "#5",
        45.2
       ],
       [
        "#7",
        66.47
       ],
       [
        "#10",
        83.61
       ],
       [
        "#15",
        115.56
       ],
       [
        "#20 C40-49mm",
        170.53
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": [
     {
      "as": "Swedish Aspen",
      "forms": [
       [
        "#5",
        null
       ],
       [
        "#10",
        null
       ],
       [
        "6-8' br 2yr",
        null
       ]
      ]
     }
    ]
   }
  },
  "creeping-juniper": {
   "mapped": false
  },
  "dwarf-american-cranberry": {
   "mapped": false
  },
  "early-forsythia": {
   "mapped": false
  },
  "false-spirea": {
   "mapped": false
  },
  "feather-reed-grass": {
   "mapped": false
  },
  "flowering-raspberry": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": null,
    "mckay": null,
    "stewart": null
   }
  },
  "froebelii-spirea": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Froebel Spirea",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "goatsbeard": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Goat's Beard",
      "forms": [
       [
        "#1",
        7.83
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "gold-crinkled-hair-grass": {
   "mapped": false
  },
  "gold-crinkled-hair-grass-sub": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Tufted Hair Grass",
      "forms": [
       [
        "#1",
        7.83
       ],
       [
        "#2",
        14.1
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Tufted Hair Grass",
      "forms": [
       [
        "#1 Container",
        9
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "gold-drop-potentilla": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Gold Drop Potentilla",
      "forms": [
       [
        "#1",
        8.17
       ],
       [
        "#2",
        14.24
       ],
       [
        "#5",
        23.79
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "goldfinger-potentilla": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Gold\ufb01nger",
      "forms": [
       [
        "#5",
        52
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Goldfinger Potentilla",
      "forms": [
       [
        "#1",
        8.17
       ],
       [
        "#2",
        14.24
       ],
       [
        "#5",
        23.79
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Goldfinger (Cinquefoil) Potentilla",
      "forms": [
       [
        "#3 Container",
        17.5
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "goldflame-spirea": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Goldflame",
      "forms": [
       [
        "#5",
        48
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Goldflame Spirea",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Goldflame Spirea",
      "forms": [
       [
        "#3 Container",
        17.75
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "goldmound-spirea": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Goldmound",
      "forms": [
       [
        "#5",
        46
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Gold Mound Spirea",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Goldmound Spirea",
      "forms": [
       [
        "#3 Container",
        17.75
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "hardy-purple-common-lilac": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Common Lilac",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Common Purple Old Fashioned Lilac",
      "forms": [
       [
        "3' Balled & Burlap",
        25.75
       ],
       [
        "4' Balled & Burlap",
        32.5
       ],
       [
        "#3 Container",
        22.5
       ],
       [
        "#5 Container",
        26.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "hardy-purple-common-lilac-2-sub": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Common Lilac",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Common Purple Old Fashioned Lilac",
      "forms": [
       [
        "3' Balled & Burlap",
        25.75
       ],
       [
        "4' Balled & Burlap",
        32.5
       ],
       [
        "#3 Container",
        22.5
       ],
       [
        "#5 Container",
        26.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "hedge-cotoneaster": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Cotoneaster..Hedge",
      "forms": [
       [
        "#3",
        32
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Peking/Hedge Cotoneaster",
      "forms": [
       [
        "#1",
        6.84
       ],
       [
        "#2",
        14.15
       ],
       [
        "#5",
        21.84
       ],
       [
        "#10",
        45.58
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Hedge / Shiny Cotoneaster",
      "forms": [
       [
        "3' Ball & Burlap",
        19.5
       ],
       [
        "#3 Container",
        16.5
       ],
       [
        "#5 Container",
        20
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "helena-maple": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Helena maple",
      "forms": [
       [
        "1.75\"",
        595
       ],
       [
        "2\"",
        635
       ],
       [
        "2.75\"",
        950
       ]
      ]
     }
    ],
    "bron": null,
    "mckay": null,
    "stewart": null
   }
  },
  "hosta-patriot": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Patriot Hosta",
      "forms": [
       [
        "#1",
        8.17
       ],
       [
        "#2",
        14.24
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Patriot Hosta Plantain Lily",
      "forms": [
       [
        "#1 Container",
        8.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "ivory-halo-dogwood": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Ivory halo",
      "forms": [
       [
        "#5",
        58
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Ivory Halo\u00ae Dogwood",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ],
       [
        "#10",
        45.53
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Ivory Halo\u00ae Variegated Dogwood",
      "forms": [
       [
        "#3 Container",
        23.75
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "karl-foerster-reed-grass": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Carl forester reed grass",
      "forms": [
       [
        "#1",
        14
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Foerster's Feather Reed Grass",
      "forms": [
       [
        "#1",
        7.83
       ],
       [
        "#2",
        14.1
       ],
       [
        "#5",
        21.84
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Karl Foerster Feather Reed Grass",
      "forms": [
       [
        "#1 Container",
        7.75
       ],
       [
        "#3 Container",
        20.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "lady-fern": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Ladyfern",
      "forms": [
       [
        "#1",
        7.83
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "late-lilac": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Villosa Late Lilac",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "lodgepole-pine": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Lodgepole pine, Idaho. Specimen trees",
      "forms": [
       [
        "8'-9'",
        875
       ],
       [
        "9'-10'",
        965
       ]
      ]
     },
     {
      "as": "Alaska grown Lodge pole pine",
      "forms": [
       [
        "per ft.",
        32
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Lodgepole Pine",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        15.81
       ],
       [
        "#5",
        26.11
       ],
       [
        "#10",
        81.37
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "miss-canada-lilac": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Lilac Miss Canada",
      "forms": [
       [
        "#5",
        52
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Miss Canada Lilac",
      "forms": [
       [
        "#2 Shrub",
        16.76
       ],
       [
        "#5 Shrub",
        25.07
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "miss-kim-lilac": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Miss Kim",
      "forms": [
       [
        "#5",
        60
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Miss Kim Lilac",
      "forms": [
       [
        "#1 Shrub",
        8.93
       ],
       [
        "#2 Shrub",
        16.76
       ],
       [
        "#5 Shrub",
        25.07
       ],
       [
        "#5 T/G",
        57.3
       ],
       [
        "#10 Shrub",
        47.57
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Miss Kim Compact Lilac",
      "forms": [
       [
        "#3 Container",
        20
       ],
       [
        "#5 Container",
        22.5
       ]
      ]
     }
    ],
    "stewart": [
     {
      "as": "Miss Kim Lilac",
      "forms": [
       [
        "1QT",
        null
       ]
      ]
     }
    ]
   }
  },
  "overdam-reed-grass": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Overdam Var. Feather Reed Grass",
      "forms": [
       [
        "#1",
        7.83
       ],
       [
        "#2",
        14.1
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Overdam Variegated Feather Reed Grass",
      "forms": [
       [
        "#1 Container",
        10.5
       ],
       [
        "#3 Container",
        22.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "paper-birch": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Alaska paper birch",
      "forms": [
       [
        "1.5\"",
        175
       ],
       [
        "1.75\"",
        198
       ],
       [
        "2\"",
        238
       ],
       [
        "2.25\"",
        278
       ],
       [
        "2.5\"",
        325
       ],
       [
        "2.75\"",
        395
       ],
       [
        "3\"",
        495
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Paper Birch",
      "forms": [
       [
        "#5",
        45.2
       ],
       [
        "#5 Clump",
        49.76
       ],
       [
        "#10",
        83.61
       ],
       [
        "#10 Clump",
        83.94
       ],
       [
        "#15",
        115.56
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": [
     {
      "as": "Paper Birch",
      "forms": [
       [
        "#15",
        null
       ],
       [
        "1\" br 1yr",
        null
       ]
      ]
     },
     {
      "as": "Paper Birch Clump",
      "forms": [
       [
        "1\"",
        null
       ],
       [
        "1\u00bc\"",
        null
       ]
      ]
     }
    ]
   }
  },
  "parkland-pillar-birch": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Parkland Pillar\u2122 Birch",
      "forms": [
       [
        "#5 Low Branch FE",
        49.76
       ],
       [
        "#10 Low Branch",
        83.94
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Birch Parkland Pillar Aian Columnar Single FE\u00ae",
      "forms": [
       [
        "#15 Container",
        112.5
       ]
      ]
     }
    ],
    "stewart": [
     {
      "as": "Parkland Pillar Birch",
      "forms": [
       [
        "#10",
        null
       ]
      ]
     }
    ]
   }
  },
  "pink-beauty-potentilla": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Pink beauty",
      "forms": [
       [
        "#5",
        52
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Pink Beauty Potentilla",
      "forms": [
       [
        "#1",
        8.17
       ],
       [
        "#2",
        14.24
       ],
       [
        "#5",
        23.79
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "prairiefire-crabapple": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Prairie \ufb01re crabapple",
      "forms": [
       [
        "#20",
        225
       ]
      ]
     }
    ],
    "bron": null,
    "mckay": [
     {
      "as": "Prairifire Flowering Crab",
      "forms": [
       [
        "#15 Container",
        110
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "quaking-aspen": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Quaking aspen",
      "forms": [
       [
        "1.75\"",
        185
       ],
       [
        "2\"",
        225
       ],
       [
        "2.25",
        250
       ],
       [
        "2.5\"",
        295
       ],
       [
        "2.75\"",
        345
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Quaking/Trembling Aspen",
      "forms": [
       [
        "#1 Single",
        7.93
       ],
       [
        "#2 Single",
        16.62
       ],
       [
        "#5 Single",
        39.98
       ],
       [
        "#5 Clump",
        45.67
       ],
       [
        "#10 Single",
        77.43
       ],
       [
        "#10 Clump",
        81.37
       ],
       [
        "#15 Single",
        104.21
       ],
       [
        "#15 Clump",
        107.2
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Quaking Aspen / White Poplar Single",
      "forms": [
       [
        "#15 Container (1 1/4\"- 1 3/4\")",
        115
       ]
      ]
     },
     {
      "as": "Quaking Aspen / White Poplar Clump",
      "forms": [
       [
        "10' Balled & Burlap",
        160
       ],
       [
        "12' Balled & Burlap",
        175
       ],
       [
        "14' Balled & Burlap",
        195
       ],
       [
        "#5 Grow Bag",
        24.75
       ],
       [
        "#15 Container",
        125
       ]
      ]
     }
    ],
    "stewart": [
     {
      "as": "Quaking Aspen",
      "forms": [
       [
        "#10",
        null
       ],
       [
        "1\u00bc\" br 2yr",
        null
       ]
      ]
     },
     {
      "as": "Quaking Aspen Clump",
      "forms": [
       [
        "6' 1yr",
        null
       ]
      ]
     }
    ]
   }
  },
  "red-twig-dogwood": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Bailey red twig Dogwood",
      "forms": [
       [
        "#5",
        48
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Red Osier Dogwood",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ],
       [
        "#10",
        45.53
       ]
      ]
     },
     {
      "as": "Bailey Red Twig Dogwood",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Bailey Red-Twig Dogwood",
      "forms": [
       [
        "#3 Container",
        18
       ],
       [
        "#5 Container",
        22
       ]
      ]
     }
    ],
    "stewart": [
     {
      "as": "Red Osier Dogwood",
      "forms": [
       [
        "#5",
        null
       ]
      ]
     },
     {
      "as": "Bailey Redtwig Dogwood",
      "forms": [
       [
        "#5",
        null
       ]
      ]
     }
    ]
   }
  },
  "rugosa-rose": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Rugosa rose, red",
      "forms": [
       [
        "#3",
        38
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "Rugosa Rose",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Hansa Rugosa Rose",
      "forms": [
       [
        "#3 Container",
        17.25
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "savin-juniper": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Savin Juniper",
      "forms": [
       [
        "#2",
        17.09
       ],
       [
        "#5",
        25.97
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "scotch-pine": {
   "mapped": false
  },
  "siberian-crabapple": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": null,
    "mckay": null,
    "stewart": null
   }
  },
  "subalpine-fir-arizonica": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": null,
    "mckay": null,
    "stewart": null
   }
  },
  "sweet-woodruff": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Sweet Woodruff",
      "forms": [
       [
        "#1",
        8.17
       ]
      ]
     }
    ],
    "mckay": null,
    "stewart": null
   }
  },
  "vanhoutte-spirea": {
   "mapped": true,
   "offers": {
    "seedntree": null,
    "bron": [
     {
      "as": "Renaissance Spirea",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        14.53
       ],
       [
        "#5",
        22.98
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Renaissance Bridal Wreath Spirea",
      "forms": [
       [
        "#3 Container",
        17.75
       ]
      ]
     }
    ],
    "stewart": null
   }
  },
  "white-spruce": {
   "mapped": true,
   "offers": {
    "seedntree": [
     {
      "as": "Alaska White spruce, Black hills spruce. Ak. grown",
      "forms": [
       [
        "5'-6'",
        165
       ],
       [
        "6'-7'",
        195
       ],
       [
        "7'-8'",
        225
       ]
      ]
     },
     {
      "as": "Alaskan white spruce \ufb01eld grade",
      "forms": [
       [
        "per ft.",
        20
       ]
      ]
     }
    ],
    "bron": [
     {
      "as": "White Spruce",
      "forms": [
       [
        "#1",
        7.88
       ],
       [
        "#2",
        15.81
       ],
       [
        "#5",
        26.11
       ],
       [
        "#10",
        81.37
       ],
       [
        "#15",
        104.21
       ]
      ]
     }
    ],
    "mckay": [
     {
      "as": "Black Hills White Spruce",
      "forms": [
       [
        "#3 Container",
        27
       ],
       [
        "#5 Container",
        40
       ],
       [
        "5' Balled & Burlap",
        169.25
       ]
      ]
     }
    ],
    "stewart": [
     {
      "as": "White Spruce",
      "forms": [
       [
        "#25 6-7''",
        null
       ]
      ]
     }
    ]
   }
  },
  "yellow-potentilla": {
   "mapped": false
  }
 }
};
